# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

schedules:
- cron: '0 0 * * *'
  displayName: Midnight Build For Centos9s Ansible Image
  branches:
    include:
    - main
  always: true

trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest'
  dockerImageName: 'docker-centos9s-ansible'
  dockerContainerName: 'test-container'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: 'Linux'
    steps:
    - checkout: self
      clean: true
      fetchDepth: 1

    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(dockerImageName)
        command: build
        dockerfile: '**/Dockerfile'

- stage: Test
  displayName: Test Image
  dependsOn: Build
  jobs:
  - job: TestImage
    displayName: Test Image
    pool: 'Linux'
    steps:
    - task: CmdLine@2
      name: CreateContainer
      displayName: Create Container from Image
      inputs:
        script: 'docker run --name $(dockerContainerName) -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cgroupns=host $(dockerImageName)'
        failOnStderr: true
    - task: CmdLine@2
      name: RunCMDinContainer
      displayName: Run command ansible in Container
      inputs:
        script: 'docker exec --tty $(dockerContainerName) env TERM=xterm ansible --version'
        failOnStderr: true

- stage: Release
  displayName: Push Image
  dependsOn: Test
  jobs:
  - job: PushImage
    displayName: Push Image to Docker
    pool: 'Linux'
    steps:
    - task: Docker@2
      inputs:
        repository: $(dockerImageName)
        containerRegistry: 'Docker Hub (ZHLZack)'
        command: 'push'